checkbugs: handle release candidates properly
The script was crashing because it didn't know about release candidates,
such as '26.0rc1':

    Traceback (most recent call last):
      File "../beaker-administrivia/checkbugs.py", line 439, in <module>
	main()
      File "../beaker-administrivia/checkbugs.py", line 318, in main
	options.milestone = get_default_milestone()
      File "../beaker-administrivia/checkbugs.py", line 292, in get_default_milestone
	return increment_major(current_version())
      File "../beaker-administrivia/checkbugs.py", line 72, in increment_major
	major, minor = [int(piece) for piece in version.split('.')]
    ValueError: invalid literal for int() with base 10: '0rc1'

When a release candidate is the latest tag on the develop branch, it
means we want to check the bugs for the final release of the same
version (in this case, 26.0 not 27.0).